### ISSUE TITLE
'popupstate' cannot be used as a jsx component

### ISSUE THREAD

**Issue by enoh-barbu** [jcoreio/material-ui-popup-state#100]
Related to https://github.com/facebook/react/issues/24304
Please have a look on this bug

**Comment by omridevk** [comment]
for now downgrading react types to 17, solves the issues.

**Comment by enoh-barbu** [comment]
yes, using `resolutions`... Just saying this because I had the issue using popupState

**Comment by jedwards1211** [comment]
fixed in https://github.com/jcoreio/material-ui-popup-state/commit/ae8c2864678316e624a28423d0f73b1786945a30

Sorry for the long delay...finally rewrote the package in TS.  The situation with TS defs for React is really bad...
