### ISSUE TITLE
bindHover and bindFocus conflict on input

### ISSUE THREAD

**Issue by vibl** [jcoreio/material-ui-popup-state#102]
When I use both `bindHover` and `bindFocus` on an input, they conflict: `bindHover` makes the popup close on blur, when the focus is still on the input.

A workaround could be to add a `bindHoverOrFocus` function.

But it might be better (if at all possible) to store the states `hovered` and `focused` somewhere in the hook and not close the popup if if one becomes false when the other is still true.

What do you think?

**Comment by jedwards1211** [comment]
Yeah, sounds like that's the best solution.  Will do!

**Comment by jedwards1211** [comment]
okay I got `bindHover` + `bindFocus` working properly together 👍

**Comment by vibl** [comment]
Wow, the fix was also very fast! Thank you.
