### ISSUE TITLE
Error in production when building with vite 2.9

### ISSUE THREAD

**Issue by samuelatefah** [jcoreio/material-ui-popup-state#108]
First and foremost, thank you for this package. It has helped me easily manage the state of Popup components in a project that I am working on!

Unfortunately, I am experiencing a bug in my production environment that is similar to issue #88. The issue does not occur in my dev environment. However, in my production environment which utilizes the `vite build` script, I am receiving the following error:

```
Uncaught TypeError: te.usePopupState is not a function
```

This is the import statement that I am using: 

```
import { usePopupState } from "material-ui-popup-state/hooks";
```

Would greatly appreciate it if someone could help me resolve this issue. Thanks! 

I am using:
react: 18.2.0
Vite: 2.9.9
material-ui-popup-state: 4.0.1
@mui/material: 5.3.0

**Comment by jedwards1211** [comment]
Ah sorry for the difficulty,
`import { usePopupState } from "material-ui-popup-state/es/hooks"` should work. (Note the `/es/`)

I need to add export maps though.  I'll try to do that soon, it'll have to be a breaking change.

**Comment by ninoman** [comment]
Hello, I have the same issue and the proposed solution is not working. Now I'm getting this error

Internal server error: Missing "./es/hooks" export in "material-ui-popup-state" package

**Comment by ninoman** [comment]
and for a strange reason the initial error is not thrown for every usage, I have used it in the 4 different components, and the error is thrown only for one

**Comment by jedwards1211** [comment]
wait a minute, I wasn't thinking, the `package.json` already has an `export` map so `import { usePopupState } from "material-ui-popup-state/hooks";` should work.  I don't use Vite and don't know what its deal is, and the inconsistency @ninoman mentions is sus.  Maybe file an issue with Vite?

**Comment by ssh000** [comment]
@ninoman just encountered the same issue when I started to split my app into chunks using React.lazy and vite 3.0.3. Workaround for me is to move `material-ui-popup-state` into a separate chunk using `rollupOptions.output.manualChunks`. What I also found is if I change `node_modules/material-ui-popup-state/package.json` `"sideEffects": true` then it works for my production build. Apparently vitejs is trying to use tree shaking on `material-ui-popup-state` but it has side effects.

**Comment by ninoman** [comment]
Hey @ssh000 I'm going to try `rollupOptions.output.manualChunks` option you mentioned, currently what I was doing as a workaround, was importing whole material-ui-popup-state and just spreading it in the file

**Comment by jedwards1211** [comment]
@ssh000
> Apparently vitejs is trying to use tree shaking on material-ui-popup-state but it has side effects.

I don't really get it.  Maybe Vite or Rollup is considering [the error I throw if `React.useState` is missing](https://github.com/jcoreio/material-ui-popup-state/blob/master/src/hooks.js#L7) a side effect?  Or maybe it considers [my printed warnings cache](https://github.com/jcoreio/material-ui-popup-state/blob/master/src/core.js#L6) a side effect?  But I thought `"sideEffects": false` is supposed to be a hint to bypass side effect detection...

Could you let me know if deleting those things (in your `node_modules/material-ui-popup-state/hooks.js` affects the production build?

But I still don't understand why `usePopupState` would be (apparently) tree-shaking `usePopupState` away when `"sideEffects": false` but not when you change it to `true`.

**Comment by jedwards1211** [comment]
Also what exactly is happening with the chunk output if you're not using `rollupOptions.output.manualChunks`?

**Comment by jedwards1211** [comment]
If anyone can create a minimum repro repository I'm happy to play around with it.

**Comment by ssh000** [comment]
@jedwards1211 Hey Andy, here is a repo with reproduced bug https://github.com/ssh000/material-ui-popup-state-bug if you will navigate to a second chunk (/chunk-two) and refresh the page you will see the error. This is happening because for some reason rollup and vite.js put material-ui-popup-state only in the first chunk 🤔 I hope this is will help! 
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/662758/183849575-0d99a8a2-3d0e-4428-8e75-e90ba4e0e5b0.png">

**Comment by jedwards1211** [comment]
Okay, I'll look at that soon...should it be putting material-ui-popup-state in more than one chunk though?  Theoretically each chunk that needs it could load the material-ui-popup-state chunk first, right?

**Comment by ssh000** [comment]
Hey Andy, it should go to a separate module as far as I understand it!

**Comment by liaokaime** [comment]
> 

I solved my problem in this way
```javascript
import { splitVendorChunkPlugin } from 'vite'
export default defineConfig({
  plugins: [splitVendorChunkPlugin()]
})
```

**Comment by HasaanSultan** [comment]
I am facing same issue, with Vite 3.1.3
