### ISSUE TITLE
onMouseOver/onMouseLeave/etc. functions are not stable

### ISSUE THREAD

**Issue by Shaddix** [jcoreio/material-ui-popup-state#110]
For usual `<div>` or other html components this is not an issue.
But if I pass these functions through several components these intermediate components rerender too often.

I need this component hierarchy when I want to only show a single Popper while there are many `anchorEl`s.

If it's not hard to make these functions stable, I guess it will bring value.

P.S. I could provide a PR if you agree that this is useful

**Comment by jedwards1211** [comment]
Okay, this will be a fairly large change, we need to rewrite core.js to use hooks and rewrite <PopupState> to use the hooks internally.  Which means dropping support for React < 16.8

**Comment by Shaddix** [comment]
I guess, MUI [requires React 17+](https://mui.com/material-ui/getting-started/supported-platforms/#react), so for 
material-ui-popup-state v2+ requiring React 17+ shouldn't be a problem as well, or am I wrong?

Unfortunately I forgot about HOC version (`<PopupState>`), which I agree might not be as easy.. but if you're ok I could try, maybe it will work out

**Comment by jedwards1211** [comment]
Actually i forget, this project depends on MUI v5 now
