### ISSUE TITLE
Attempted import error: 'usePopupState' is not exported

### ISSUE THREAD

**Issue by wimil** [jcoreio/material-ui-popup-state#112]
```
Attempted import error: 'usePopupState' is not exported from 'material-ui-popup-state/hooks' (imported as 'usePopupState').
```

i am trying to compile my code to production and i am running into this error, i am using this plugin and i suspect it has something to do with it. if someone can help me please.

plugins:
"react-app-rewire-alias"
"react-app-rewired"

I get this error when I go to build my application.

**Comment by wimil** [comment]
can someone help me with this, I'm stuck and can't compile my application for production.

**Comment by jedwards1211** [comment]
sorry for the delay, it doesn't sound like this issue is caused by this package, and I've never tried using those plugins, but if you post more information about your config I can try to help

**Comment by edbella** [comment]
I encountered this error as well using the hooks derivative.

Only way forward here is to use the HOC `PopupState`

**Comment by jedwards1211** [comment]
I'm going to close this as stale. Let me know if you still have problems
