### ISSUE TITLE
After bump to 5.0.0 bindTrigger stop working

### ISSUE THREAD

**Issue by darkkatarsis** [jcoreio/material-ui-popup-state#114]
As I mentioned in the title, after bumping up to the latest version, I noticed that the trigger does not change state.

React version: 18.2.0

Example code that stopped working

```
import * as React from 'react'
import Button from '@mui/material/Button'
import Menu from '@mui/material/Menu'
import MenuItem from '@mui/material/MenuItem'
import {
  usePopupState,
  bindTrigger,
  bindMenu,
} from 'material-ui-popup-state/hooks'

const MenuPopupState = () => {
  const popupState = usePopupState({ variant: 'popover', popupId: 'demoMenu' })
  return (
    <div>
      <Button variant="contained" {...bindTrigger(popupState)}>
        Open Menu
      </Button>
      <Menu {...bindMenu(popupState)}>
        <MenuItem onClick={popupState.close}>Cake</MenuItem>
        <MenuItem onClick={popupState.close}>Death</MenuItem>
      </Menu>
    </div>
  )
}

export default MenuPopupState
```

**Comment by jedwards1211** [comment]
I wasn't able to reproduce this myself, but I did catch some other issues like with the ESM exports and just released v5.0.1.  Can you see if that version fixes the problem?  If not can you make a repo that reproduces the issue?

**Comment by jedwards1211** [comment]
Okay I believe I found the cause of the issue, once 5.0.3 gets released (there will be a comment on this issue), try that

**Comment by darkkatarsis** [comment]
@jedwards1211 I confirm, everything works. Thank you!
