### ISSUE TITLE
`useLayoutEffect` warnings during SSR

### ISSUE THREAD

**Issue by eugene-mohc** [jcoreio/material-ui-popup-state#115]
I believe this was introduced with version 5 and the `useEvent` hook.

Using `usePopupState` in any component that's rendered on the server causes warnings about using `useLayoutEffect` on the server.

A solution can be to create an isomorphic layout effect hook which will fallback to using `useEffect` during SSR.

```ts
export const useIsomorphicLayoutEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect
```

**Comment by cmdcolin** [comment]
i'm not a dev on this project but see this link (mostly, ignore the replies though, they are a bit misguided) https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85

changing it to a "useIsomorphic" type thing might squash the warning, but it is not really a proper solution. making it a useEffect is essentially a no-op masquerading as a useEffect.

**Comment by jedwards1211** [comment]
I'm only using `useLayoutEffect` to prevent the callback function instances from changing, so on the server side I should just forget about that and always return the function passed to `useEvent`.

**Comment by eugene-mohc** [comment]
That works too! Thank you for the speedy fix.
