### ISSUE TITLE
MUI Dialog - React does not recognize the `anchorPosition` prop on a DOM element.

### ISSUE THREAD

**Issue by mightym** [jcoreio/material-ui-popup-state#118]
I'm using material-ui-popup-state on a MUI Dialog. And I'm getting those warnings:
```
Warning: React does not recognize the `anchorEl` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `anchorel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Warning: React does not recognize the `anchorPosition` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `anchorposition` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

React does not recognize the `anchorReference` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `anchorreference` instead. If you accidentally passed it from a parent component, remove it from the DOM element
```
Is this something I can ignore or am I doing something wrong here?

**Comment by jedwards1211** [comment]
those are props for a `Popover` or `Menu` so you're probably passing the wrong props to the `Dialog`; make sure you're passing `variant: 'dialog'` to `usePopupState()` and passing `{...bindDialog(popupState)}` props to the `<Dialog>`.

**Comment by mightym** [comment]
This is my popupState and the according render function: 

```
const popupState = usePopupState({
   variant: 'dialog',
   popupId: 'settingsDialog',
});

return (
  <SettingsDialog
     popupState={popupState}
  />
);
```
and this my `Dialog` Component: 

```
export const SettingsDialog = ({
  popupState,
}) => {
  return (
    <Dialog
      {...bindMenu(popupState)}
    >
      <DialogTitle onClose={popupState.close}>
        Settings
      </DialogTitle>
    </Dialog>
  )
};
```

**Comment by mightym** [comment]
Oh I just realize there is another Warning/Error: 

`[material-ui-popup-state] WARNING – "eventOrAnchorEl should be defined if setAnchorEl is not used"
printWarning — react-dom.development.js:86`

Maybe I'm doing something wrong there...

**Comment by mightym** [comment]
Oh @jedwards1211 ... thanks a lot :)

**Comment by mightym** [comment]
@jedwards1211 and the error about 
```
[material-ui-popup-state] WARNING – "eventOrAnchorEl should be defined if setAnchorEl is not used"
```
can be ignored or do I need to set `eventOrAnchorEl` ?

**Comment by jedwards1211** [comment]
Oh thanks for asking, looking at the code, I need to prevent it from warning about that when `variant: 'dialog'` is used.
