### ISSUE TITLE
'HoverMenu' cannot be used as a JSX component

### ISSUE THREAD

**Issue by mojtaba-hajishah** [jcoreio/material-ui-popup-state#119]
I get this Typescript error when I use the HoverMenu component:

```
'HoverMenu' cannot be used as a JSX component.
 Its element type 'ReactElement<any, any> | Component<MenuProps, any, any> | null' is not a valid JSX element.
 Type 'Component<MenuProps, any, any>' is not assignable to type 'Element | ElementClass | null'.
 Type 'Component<MenuProps, any, any>' is not assignable to type 'ElementClass'.
 The types returned by 'render()' are incompatible between these types.

```

**Comment by jedwards1211** [comment]
Sorry for the long delay, can you tell me what version of this package and of TypeScript you're using?
This is pretty mysterious, in `material-ui-popup-state` 4.1.0 and in v5 it's been declared as `HoverMenu: React.ComponentType<MenuProps>`, which should be pretty foolproof, and it's weird that `Component` is winding up among the possible element types.

**Comment by jedwards1211** [comment]
I'm going to close this as stale.  Let me know if you still have problems
