### ISSUE TITLE
React.createElement: type is invalid in Next.js 13

### ISSUE THREAD

**Issue by hamid842** [jcoreio/material-ui-popup-state#125]
I'm getting this warning and Internal error into Next 13:
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at HoverMenu (webpack-internal:///(ssr)/./node_modules/material-ui-popup-state/es/HoverMenu.mjs:17:16)
    at MenuButtons (webpack-internal:///(ssr)/./src/components/global/menu-buttons.tsx:19:24)
`

**Comment by rajdtta** [comment]
@jedwards1211 Is this something you're able to look into? I tried digging into it earlier this week, but wasn't able to make much headway.

**Comment by jedwards1211** [comment]
Sorry for the delay, yes I'll look into it today

**Comment by jedwards1211** [comment]
Ugh this is a nasty and complicated webpack module resolution issue.

Next appears to set this module alias by default:

```
  '@mui/material$': '/Users/andy/gh/mui-popup-state-next-13/node_modules/@mui/material/index.js',
```

I think I should probably file a bug in Next.js about this, but I'm still trying to investigate why they did this in the first place.

For me this config tweak worked around the issue...hopefully it doesn't break anything for you?

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    if (config.resolve.alias) delete config.resolve.alias["@mui/material$"];
    return config;
  },
};

module.exports = nextConfig;
```

**Comment by jedwards1211** [comment]
https://github.com/vercel/next.js/issues/57285

**Comment by jedwards1211** [comment]
Really don't know the best way to solve that issue with Next.js' default config so I just implemented a workaround in this package...should get released soon
