### ISSUE TITLE
Popper example with arrowRef?

### ISSUE THREAD

**Issue by adammlr** [jcoreio/material-ui-popup-state#13]
Can this library be used with a Popper that has an arrow?  What property is used as the arrowRef?
Thanks!
https://material-ui.com/components/popper/#scroll-playground

**Comment by spmsupun** [comment]
Did you find it ?

**Comment by kiran-aghor** [comment]
This is how I use popper with arrow.

`

        const [arrowRef, setArrowRef] = React.useState<HTMLSpanElement | null>(null);

        <StyledPopper
          {...bindPopper(popupState)}
          transition
          placement='right'
          disablePortal={disablePortal}
          modifiers={{
            preventOverflow: {
              enabled: true,
              boundariesElement: 'scrollParent',
            },
            arrow: {
              enabled: true,
              element: arrowRef,
            },
            flip: {
              enabled: true,
            },
          }}
          $color={colorVariant}
        >....
`

**Comment by a2441918** [comment]
How do you use setArrowRef?

**Comment by em2ai-terence** [comment]
Unfortunately we're not able to view the source code for the example with [ArrowRef](https://mui.com/material-ui/react-popper/#scroll-playground).

This is what I'm able to come up with:

`
const [showSettingsPopover, setShowSettingsPopover] = useState(false);
const toggleSettingsPopover = e => {
    setSettingsPopoverAnchorEl(
      settingsPopoverAnchorEl ? null : e.currentTarget
    );
    setShowSettingsPopover(!showSettingsPopover);
  };

return (
          <div>
               <SettingsIcon fontSize="large" onClick={toggleSettingsPopover} />
              <Popper
                open={showSettingsPopover}
                anchorEl={settingsPopoverAnchorEl}
                modifiers={[
                  {
                    name: "arrow",
                    enabled: true,
                    options: {
                      element: arrowRef,
                    },
                  },
                ]}
              >
                <div ref={setArrowRef}>
                  <MenuItem>
                    <Checkbox />
                    <ListItemText primary="Test" />
                  </MenuItem>

                  <MenuItem>
                    <Checkbox />
                    <ListItemText primary="Test 2" />
                  </MenuItem>
                </div>
              </Popper>
    </div>
`
