### ISSUE TITLE
Reposition the Menu on initial opening.

### ISSUE THREAD

**Issue by Shemrock3267** [jcoreio/material-ui-popup-state#133]
I had an issue with custom `Chip` component from `@mui/material` in conjunction with `Menu` & `MenuItem`.
Used [your demo](https://jcoreio.github.io/material-ui-popup-state/#trigger-menu) and it worked almost fine.
**Issue** is that on initial opening it was **slightly to the right**, while if I open it for the second time it positioned well.

**Screenshots**:
`Initial click`
<img width="200" alt="Screenshot 2024-04-09 at 10 40 56" src="https://github.com/jcoreio/material-ui-popup-state/assets/10697124/7645090c-9a71-4d4a-be08-cbe737c0c9dc">
`Second click`
<img width="223" alt="Screenshot 2024-04-09 at 10 41 05" src="https://github.com/jcoreio/material-ui-popup-state/assets/10697124/e4fd508c-3d53-42be-a799-b5b80b0963e4">

I managed to fix it via `useEffect`:
```
const popupState = usePopupState({ variant: 'popover', popupId: 'profilePopup' });
const ref = useRef<HTMLDivElement>(null);

useEffect(() => {
  // Reposition the menu when it opens for the first time
  if (popupState.isOpen) {
    popupState.setAnchorEl(ref.current);
  }
}, [popupState, popupState.isOpen]);  
```
Maybe you should add something like this into the library.
Cheers

**Comment by Shemrock3267** [comment]
`UPDATE`
This `fix` introduces another issue:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```

Not sure how to fix it.

**Comment by jedwards1211** [comment]
I think this will be hard to debug without seeing exactly what's happening.  Do you think you could add a component that reproduces this issue to the demo app in a fork of this repo?  Then i could investigate

**Comment by prma85** [comment]
I had the same problem, and my fix was to add the binding to the item above that had both the menu and the chip instead of just the menu.
I hope this helps

```tsx
 <Box>
      <Link
        key={title}
        href={path}
        {...bindHover(popupState)}
        {...bindFocus(popupState)}
        className={active ? 'active' : ''}
      >
        <ListItemText>
          {title} {hasSubMenu && <ChevronDown viewBox='0 0 18 18' fontSize='inherit' />}
        </ListItemText>
        {hasSubMenu && <ArrowBox>
        <Fade in={popupState.isOpen} timeout={500} appear={true}>
          {<Arrow component='span' className='arrow' />}
        </Fade>
        </ArrowBox>}
      </Link>
      {hasSubMenu && (
        <>
          <CascadingMenu
            popupState={popupState}
            anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
            transformOrigin={{ vertical: 'top', horizontal: 'center' }}
            open
          >
            {items.map((item) =>
              item.items && item.items.length > 0 ? (
                <CascadingSubmenu
                  key={cleanString(item.title + 'cascading-menu')}
                  popupId={cleanString(item.title + 'cascading-menu')}
                  title={item.title}
                  TransitionComponent={Fade}
                  transitionDuration={500}
                  open
                >
                  {item.items.map((subItem) => (
                    <CascadingMenuItem key={cleanString(subItem.title)} href={subItem.path}>
                      <ListItemText primary={subItem.title} />
                    </CascadingMenuItem>
                  ))}
                </CascadingSubmenu>
              ) : (
                <CascadingMenuItem key={`${item.title}-${item.path}`}>
                  <ListItemText primary={item.title} />
                </CascadingMenuItem>
              )
            )}
          </CascadingMenu>
        </>
      )}
    </Box>
```

**Comment by jedwards1211** [comment]
@prma85  can you share what your `CascadingMenu` and `CascadingSubmenu` implementations are?

**Comment by prma85** [comment]
> @prma85  can you share what your `CascadingMenu` and `CascadingSubmenu` implementations are?

It is the same illustrated here https://jcoreio.github.io/material-ui-popup-state/#cascading-hover-menus

**Comment by Shemrock3267** [comment]
> I had the same problem, and my fix was to add the binding to the item above that had both the menu and the chip instead of just the menu. I hope this helps
> 
> ```tsx
>  <Box>
>       <Link
>         key={title}
>         href={path}
>         {...bindHover(popupState)}
>         {...bindFocus(popupState)}
>         className={active ? 'active' : ''}
>       >
>         <ListItemText>
>           {title} {hasSubMenu && <ChevronDown viewBox='0 0 18 18' fontSize='inherit' />}
>         </ListItemText>
>         {hasSubMenu && <ArrowBox>
>         <Fade in={popupState.isOpen} timeout={500} appear={true}>
>           {<Arrow component='span' className='arrow' />}
>         </Fade>
>         </ArrowBox>}
>       </Link>
>       {hasSubMenu && (
>         <>
>           <CascadingMenu
>             popupState={popupState}
>             anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
>             transformOrigin={{ vertical: 'top', horizontal: 'center' }}
>             open
>           >
>             {items.map((item) =>
>               item.items && item.items.length > 0 ? (
>                 <CascadingSubmenu
>                   key={cleanString(item.title + 'cascading-menu')}
>                   popupId={cleanString(item.title + 'cascading-menu')}
>                   title={item.title}
>                   TransitionComponent={Fade}
>                   transitionDuration={500}
>                   open
>                 >
>                   {item.items.map((subItem) => (
>                     <CascadingMenuItem key={cleanString(subItem.title)} href={subItem.path}>
>                       <ListItemText primary={subItem.title} />
>                     </CascadingMenuItem>
>                   ))}
>                 </CascadingSubmenu>
>               ) : (
>                 <CascadingMenuItem key={`${item.title}-${item.path}`}>
>                   <ListItemText primary={item.title} />
>                 </CascadingMenuItem>
>               )
>             )}
>           </CascadingMenu>
>         </>
>       )}
>     </Box>
> ```

From the looks of it that should work. Thanks for help!

**Comment by jedwards1211** [comment]
@Shemrock3267 was your issue resolved?
