### ISSUE TITLE
React does not recognize the `ModalClasses` prop on a DOM element.

### ISSUE THREAD

**Issue by kvandake** [jcoreio/material-ui-popup-state#15]
I get the following error in the console.

> Warning: React does not recognize the `ModalClasses` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `modalclasses` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Popover))
    in ForwardRef(Popover) (created by WithStyles(ForwardRef(Popover)))
    in WithStyles(ForwardRef(Popover)) (created by ForwardRef)
    in ForwardRef (created by WithStyles(ForwardRef))

react: 16.12.0
material-UI: 4.7.2
material-ui-popup-state: 1.4.1

**Comment by jedwards1211** [comment]
Thanks for reporting this, fix should get published in a moment!  There were some confusing changes in MUI 4 regarding passing classes to a Modal.
