### ISSUE TITLE
Issue after updating to newest version with hoverPopover 

### ISSUE THREAD

**Issue by ElectricCodeGuy** [jcoreio/material-ui-popup-state#152]
## Description
After upgrading to the latest version, I'm getting a TypeScript error with `HoverPopover` component from `material-ui-popup-state`.

## Error Message
```typescript
'HoverPopover' cannot be used as a JSX component.
Its type 'ComponentType<PopoverProps>' is not a valid JSX element type.
  Type 'ComponentClass<PopoverProps, any>' is not assignable to type 'ElementType'.
    Type 'ComponentClass<PopoverProps, any>' is not assignable to type 'new (props: any, deprecatedLegacyContext?: any) => Component<any, any, any>'.
      Property 'refs' is missing in type 'Component<PopoverProps, any, any>' but required in type 'Component<any, any, any>'
```

## Code Example
```jsx
<PopupState variant="popover" popupId="profile-menu">
  {(popupState) => (
    <>
      <Button
        {...bindHover(popupState)}
        component={Link}
        href="/xxx"
        prefetch={false}
        onMouseEnter={() => router.prefetch('/xxx')}
        endIcon={<KeyboardArrowDownIcon />}
        sx={linkStyleDesktop}
        className={isActive('/xxx') ? 'active' : ''}
      >
        Min Profil
      </Button>
      <HoverPopover
        {...bindPopover(popupState)}
        anchorOrigin={{
          vertical: 'bottom',
          horizontal: 'left'
        }}
        transformOrigin={{
          vertical: 'top',
          horizontal: 'left'
        }}
        disableScrollLock
      >
        <Box sx={{ py: 1 }}>
          {/* Menu items */}
        </Box>
      </HoverPopover>
    </>
  )}
</PopupState>
```

## Additional Context
- This code worked in the previous version without any type errors

**Comment by 17gstyron** [comment]
Same issue for me. Rolling back to `5.3.1` fixes

**Comment by jedwards1211** [comment]
I guess I need to make `@types/react` a peer dependency

**Comment by cyb456** [comment]
I am getting this error after updating from 5.3.1 to 5.3.3

**Comment by jedwards1211** [comment]
@cyb456 what versions of `react`, `@types/react` and `@mui/material` do you have installed?
And were you seeing the error when running `tsc` or in the editor?  If in the editor, did you try restarting the TS server?

**Comment by cyb456** [comment]
> @cyb456 what versions of `react`, `@types/react` and `@mui/material` do you have installed? Make sure `@types/react` matches your version of `react`. And were you seeing the error when running `tsc` or in the editor? If in the editor, did you try restarting the TS server?

So I had actually found it because I was removing components not used in that project anymore, and when I added it back just now to get that info for you the error is no longer present.. I guess problem solved!

**Comment by jedwards1211** [comment]
@cyb456 okay whew!  I was hoping it was something like that
