### ISSUE TITLE
iOS virtual keyboard height + scroll position causing popover to be offset every textfield key input

### ISSUE THREAD

**Issue by loongyh** [jcoreio/material-ui-popup-state#25]
Using a MUI `TextField` input in a popover `usePopupState` hook, the iOS keyboard causes the popover to shift its position. This [video](https://www.youtube.com/watch?v=5DVzIF1Zi8w) shows the glitch.

mobileSafari on iOS 13.3.1

**Comment by jedwards1211** [comment]
Huh, does this happen if you manage the state without material-ui-popup-state?

**Comment by loongyh** [comment]
The issue's probably specific to iOS mobileSafari as it does not happen on Chrome on Android. It seems to be caused by mobileSafari's behaviour when the keyboard is opened: instead of resizing the viewport, it pushes it up off-screen. The popover seems to be overcompensating for the shift.

Sources:
[The Eccentric Ways of iOS Safari with the Keyboard](https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d)
[Bug 141832 - Viewport height is taller than the visible part of the document in some mobile browsers](https://bugs.webkit.org/show_bug.cgi?id=141832)

Anyway I have resolved the issue by changing to a non-overlay alternative by wrapping the `TextField` in a MUI `Collapse` transition.

**Comment by jedwards1211** [comment]
Okay, yeah I don't think `material-ui-popup-state` could cause this, but I haven't proven it.  I need to see where I put my old testing iPhone..
