### ISSUE TITLE
[Doc] Multiple states within a map

### ISSUE THREAD

**Issue by aress31** [jcoreio/material-ui-popup-state#28]
Nice library! I am currently struggling to find the most optimal way to use the `hooks` within a map to keep track of multiple menus' state.

This is the dirty code - really not optimal - I came up with so far:
```js
export default () => {
  const resourcesMenuState = usePopupState({
    popupId: "resources",
    variant: "popover",
  });
  const servicesMenuState = usePopupState({
    popupId: "services",
    variant: "popover",
  });

  return (
    <nav>
      <MenuList disablePadding className={classes.menuList}>
        {routes.map((route) => (
          <div key={uid(route)}>
            <MenuItem
              {...(route.name === "Resources" && bindHover(resourcesMenuState))}
              {...(route.name === "Services" && bindHover(servicesMenuState))}
              // --- SNIP ---
            >
              {route.name}
            </MenuItem>
            {route.routes && (
              <Menu
                {...(route.name === "Resources" &&
                  bindMenu(resourcesMenuState))}
                {...(route.name === "Services" && bindMenu(servicesMenuState))}
                // --- SNIP ---
              >
                {route.routes.map((nestedRoute) => (
                  <MenuItem
                    key={uid(nestedRoute)}
                    // Dirty hack - can handle only 2 menus
                    onClick={
                      route.name === 'Resources'
                        ? resourcesState.close
                        : servicesState.close
                    }
                    // --- SNIP ---
                  >
                    {nestedRoute.name}
                  </MenuItem>
                ))}
              </Menu>
            )}
          </div>
        ))}
      </MenuList>
    </nav>
  );
};
```

Could you please provide an optimal example on how to achieve this?

**Comment by jedwards1211** [comment]
Does this work?

This is adapted from the [Cascading Hover Menus example](https://jcoreio.github.io/material-ui-popup-state/#cascading-hover-menus), which also shows how to close all levels of the menus on click

```js
function SubMenu({popupId, item, children}) {
  const popupState = usePopupState({
    popupId,
    variant: "popover",
  });
  const {isOpen, close} = popupState
  return (
    <React.Fragment>
      <MenuItem {...bindHover(popupState)} selected={isOpen}>
        {item}
      </MenuItem>
      <Menu {...bindMenu(servicesMenuState)} onClick={close}>
        {children}
      </Menu>
    </React.Fragment>
  );
}

export default () => {
  return (
    <nav>
      <MenuList disablePadding className={classes.menuList}>
        {routes.map((route) =>
          route.routes ? (
            <SubMenu key={uid(route)} item={route.name} popupId={route.name}>
              {route.routes.map(nestedRoute =>
                <MenuItem key={uid(nestedRoute)}>{nestedRoute.name}</MenuItem>
              )}
            </SubMenu>
          ) : (
            <MenuItem key={uid(route)}>{route.name}</MenuItem>
          )
        )}
      </MenuList>
    </nav>
  );
};
```

**Comment by aress31** [comment]
Thanks for the code snippet but how do you bind the parent `menuItem` to the `submenu`?

**Comment by jedwards1211** [comment]
`popupId` doesn't control which menu gets opened.  In fact `popupId` is optional.  All it does is set the `id` of the popup and the AIRA prop of the trigger element to the same `id`.

If you bind multiple menus to the same `popupState`, they're all going to open at once when any trigger is clicked.

`bindTrigger`/`bindHover` just controls `popupState.isOpen`, and `bindMenu` just passes `open={popupState.isOpen}` to the Menu, which is how the parent menu item is connected to the Menu in the example I have.

I can think about API changes to support using a single `popupState` like you want; if I decide to do that, you would have to pass `popupId` to `bindTrigger`/`bindHover` and `bindMenu` though.

**Comment by jedwards1211** [comment]
Also in my example instead of putting `onClick={popupState.close}` on the menu items, I put it on the menu containing them, since the click event would bubble up from the menu items.  I should probably change my example demos to work that way

**Comment by aress31** [comment]
@jedwards1211 I would vote for implementing an option in `bindMenu` to enable close `onClick`. So what do you think about the idea of exporting a setter for `popupStateID`. And lastly, documenting the optimal way of iterating over a map would be nice.

**Comment by aress31** [comment]
Any progress on this ticket?

**Comment by jedwards1211** [comment]
@aress31 just got back from a vacation.  Sorry for forgetting about this ticket.  Here's how I would recommend solving it:

```js
import Menu from "@material-ui/core/Menu";
import MenuItem from "@material-ui/core/MenuItem";
import MenuList from "@material-ui/core/MenuList";
import {
  bindMenu,
  bindTrigger,
  usePopupState,
} from "material-ui-popup-state/hooks";
import React from "react";
import { Link as RouterLink, useLocation } from "react-router-dom";
import { uid } from "react-uid";
import routes from "../../constants/routes";


function RouteMenuItem({ route }) {
  const popupState = usePopupState({
    popupId: route.name,
    variant: "popover",
  });
  const {isOpen, close} = popupState;
  return (
    <React.Fragment>
      <MenuItem
        {...route.routes && bindTrigger(popupState)}
        selected={route.path === location.pathname}
        to={!route.routes && route.path}
      >
        {route.name}
      </MenuItem>
      {route.routes && (
        <Menu
          {...bindMenu(popupState)}
          onClick={close}
          keepMounted
          anchorOrigin={{
            horizontal: "center",
            vertical: "bottom",
          }}
          getContentAnchorEl={null}
          transformOrigin={{
            horizontal: "center",
            vertical: "top",
          }}
        >
          {route.routes.map((nestedRoute) => (
            <MenuItem
              key={uid(nestedRoute)}
              component={RouterLink}
              selected={nestedRoute.path === location.pathname}
              to={nestedRoute.path}
              onClick={popupState.close}
            >
              {nestedRoute.name}
            </MenuItem>
          ))}
        </Menu>
      )}
    </React.Fragment>
  );
}

export default () => {
  return (
    <nav>
      <MenuList disablePadding className={classes.menuList}>
        {routes.map((route) => (
          <RouteMenuItem key={uid(route)} route={route} />
        )}
      </MenuList>
    </nav>
  );
};
```

Here are the reasons I'm not in favor of a setter for `popupId` or being able to use a single `usePopupState` for multiple popup menus:
* It's not really compatible with the existing API.  I can't see a way of keeping the existing API and also getting a setter for `popupId` to work
* Why re-render the entire top-level component when just one submenu is opened or closed?  With the example I gave above, only the submenu that was opened or closed rerenders.
* It would be impossible to memoize event handler callback functions.  The current implementation of `bindTrigger(popupState)` returns an object with `onClick: popupState.open`, where `popupState.open` is a memoized function.  If I made a `bindTrigger(popupState, { popupId: 'foo' })` API, then it would have to return something like `onClick: () => popupState.open({ popupId: 'foo' })`, causing the `MenuItem` to rerender each time because `onClick` is always a new function instance.

**Comment by aress31** [comment]
@jedwards1211 thank you so much! ♥

Amazing solution, that helps me a lot, I greatly simplified my code as follows:

``js
const renderMenu = () => {
  return routeConfig.map(
    (route) => {
      const popupState = usePopupState({
        popupId: uid(route),
        variant: 'popover',
      });

      return (
      route.label && (
          <React.Fragment key={uid(route)}>
            <StyledLink
              end
              href={!route.children && route.path}
              sx={{ display: { md: 'flex', xs: 'none' } }}
              {...(route.children && bindTrigger(popupState))}
            >
              {route.label}
            </StyledLink>
            {route.children &&
              renderNestedMenu(
                route.label,
                route.children,
                popupState
              )}
          </React.Fragment>
        )
      )}
  );
};

// TODO: Style active links
const renderNestedMenu = (path, routes, popupState) => (
  <Menu
    aria-labelledby='demo-positioned-button'
    id='demo-positioned-menu'
    keepMounted
    {...bindMenu(popupState)}
    PaperProps={{
      style: {
        minWidth: '20ch',
      },
    }}
    anchorOrigin={{
      horizontal: 'center',
      vertical: 'bottom',
    }}
    onClick={popupState.close}
    transformOrigin={{
      horizontal: 'center',
      vertical: 'top',
    }}
  >
    {routes.map((route) => (
      // TODO: Fix issue with LinkComponent={NavLink}
      // https://github.com/mui-org/material-ui/issues/28251
      <StyledMenuItem
        LinkComponent={NavLink}
        href='/test'
        key={uid(route)}
        onClick={popupState.close}
      >
        {route.label}
      </StyledMenuItem>
    ))}
  </Menu>
);
```

The example you provided is definitely worth adding to the documentation as it could help other people looking for the same thing.

On a side question - unrelated to this - could I kindly ask you how you would refactor the following code in a following fashion and whether your library could be adapted to this (`navigation drawer`):

```js
// TODO: Refactor the useStates code
export default () => {
  const [openServices, setOpenServices] = React.useState(false);
  const [openResources, setOpenResources] =
    React.useState(false);

  return (
    <List component='nav'>
      {routeConfig.map(
        (route) =>
          route.label && (
            <React.Fragment key={uid(route)}>
              <StyledListItemButton
                href={!route.children && route.path}
                onClick={() =>
                  route.children &&
                  ((route.label === 'Services' &&
                    setOpenServices(
                      (prevState) => !prevState
                    )) ||
                    (route.label === 'Resources' &&
                      setOpenResources(
                        (prevState) => !prevState
                      )))
                }
              >
                <ListItemText primary={route.label} />
                {route.children &&
                  ((route.label === 'Services' &&
                    (openServices ? (
                      <ExpandLess />
                    ) : (
                      <ExpandMore />
                    ))) ||
                    (route.label === 'Resources' &&
                      (openResources ? (
                        <ExpandLess />
                      ) : (
                        <ExpandMore />
                      ))))}
              </StyledListItemButton>
              {route.children &&
                ((route.label === 'Services' &&
                  renderNestedList(
                    '/services',
                    route.children,
                    openServices
                  )) ||
                  (route.label === 'Resources' &&
                    renderNestedList(
                      '/resources',
                      route.children,
                      openResources
                    )))}
            </React.Fragment>
          )
      )}
    </List>
  );
};
```

**Comment by aress31** [comment]
Answering my own question, used the same logic you used and managed to refactor my code as follows:

```js
export default () => {
  return (
    <List component='nav'>
      {routeConfig.map((route) => {
        const [state, setState] = React.useState(false);

        return (
          route.label && (
            <React.Fragment key={uid(route)}>
              <StyledListItemButton
                href={!route.children && route.path}
                onClick={() =>
                  route.children &&
                  setState((prevState) => !prevState)
                }
              >
                <ListItemText primary={route.label} />
                {route.children &&
                  (state ? <ExpandLess /> : <ExpandMore />)}
              </StyledListItemButton>
              {route.children &&
                renderNestedList(
                  route.path,
                  route.children,
                  state
                )}
            </React.Fragment>
          )
        );
      })}
    </List>
  );
};
```

**Comment by jedwards1211** [comment]
I wouldn't recommend using my library for a simple boolean toggle state, but you could refactor it similarly to my other example, just make a separate component that does a single `useState` and returns the `React.Fragment`.  You would basically have `const [open, setOpen] = React.useState(false)`, `<StyledListItemButton onClick={() => setOpen(open => !open)} />`, `open ? <ExpandLess /> : <ExpandMore />` etc

What I like to use for toggle states is a custom hook like this:

```js

import * as React from 'react'

export default function useToggle(
  initialState: boolean = false
): {|
  value: boolean,
  set: (value: boolean | ((value: boolean) => boolean)) => void,
  toggle: () => void,
  setTrue: () => void,
  setFalse: () => void,
|} {
  const [value, set] = React.useState(initialState)
  const toggle = React.useCallback(() => set((toggled) => !toggled), [])
  const setTrue = React.useCallback(() => set(true), [])
  const setFalse = React.useCallback(() => set(false), [])

  return { value, set, toggle, setTrue, setFalse }
}
```
Then you could just do
```js
const open = useToggle(false)

return (
  ...
             <StyledListItemButton
                href={!route.children && route.path}
                onClick={open.toggle}
              >
                <ListItemText primary={route.label} />
                {route.children && (open.value ? <ExpandLess /> : <ExpandMore />)}
  ...
)
```

**Comment by jedwards1211** [comment]
@aress31 be careful, calling `useState` within `map` is dangerous, will error out if the number of items being `map`ped changes (though I know in your case `routeConfig` is a constant)

**Comment by aress31** [comment]
@jedwards1211 too advanced for me, I am just a hobbyist thanks for the warning though but yeah as you said number of routes is and will remain constant so in my case I guess it is ok...
