### ISSUE TITLE
Optional popup.focus() and document.activeElement.blur()

### ISSUE THREAD

**Issue by paynecodes** [jcoreio/material-ui-popup-state#31]
Does anyone have any ideas for how we could introduce an API for making [`popup.focus()` here](https://github.com/jcoreio/material-ui-popup-state/blob/a27b97ca3d62e5689710e82229ac1e8510d0dd6e/src/hooks.js#L57) optional? I'm having to reapply focus to my input and do some tricky logic around handling user input blur vs the blur caused by this lib.

**Comment by jedwards1211** [comment]
Yeah, I didn't think about how that would cause trouble -- would `usePopupState({focusOnOpen: false, ...})` work for you?
For now I think setting `tabIndex={-1}` on the popup element will prevent it from being focusable, but I'm not 100% sure.

**Comment by paynecodes** [comment]
@jedwards1211 I believe that API would work well. The fact that it would not be a breaking change is nice too.

**Comment by paynecodes** [comment]
Here's [another place](https://github.com/jcoreio/material-ui-popup-state/blob/a27b97ca3d62e5689710e82229ac1e8510d0dd6e/src/core.js#L91-L93) causing issues.

```
if (typeof document === 'object' && document.activeElement) {
  document.activeElement.blur()
}
```

**Comment by jedwards1211** [comment]
I'm working on this...turns out if you're using a `Popover`, `Menu`, or `Modal`, you need to pass `disableAutoFocus` and `disableEnforceFocus` to it as well (with the distinction between the two being questionable... https://github.com/mui-org/material-ui/issues/17321#issuecomment-648849926)

I'm wondering, do you open the popup when the input is focused or just when it's hovered?  I'm probably going to make a `bindFocus` API.

**Comment by jedwards1211** [comment]
Also a warning, the `disableAutoFocus` docs say

> Generally this should never be set to true as it makes the modal less accessible to assistive technologies, like screen readers.

**Comment by paynecodes** [comment]
I'm using Popup state outside the context of `Popover`, `Menu`, or `Modal`. Instead, the reason I'm dropping down to this level is to re-implement some of what's going on in those components while forging my own path. I'm not sure this library should care about input focus vs hover, but it's after focus and after an input animation completes. Please let me know if I can be more helpful.

**Comment by jedwards1211** [comment]
Sounds like it might be easier to do with CSS `:focus` pseudoclass, and use `transition-delay` to delay appearance as long as the input animation takes, as a rough example:

```css
.input-group {
  position: relative;
}
.input-popup {
  visibility: hidden;
  position: absolute;
  top: 100%;
  left: 0;
  transition: visibility 0.1s linear;
  transition-delay: 0.2s;
}
.input-group > input:focus + .input-popup {
  visibility: visible;
}
```

```jsx
<div className="input-group">
  <input />
  <div className="input-popup">
    {content}
  </div>
</div>
```

In any case I'm happy to add a `disableAutoFocus` option that blocks the `focus()` and `blur()` calls I make.

**Comment by paynecodes** [comment]
@jedwards1211 My issue is with the `focus()` and `blur()` calls. Without the `disableAutoFocus` API, I'm resorting to awkward things like the following:

```ts
// If transitioning from closed to open
// focus the input, because popupState.open will blur `document.activeElement`
React.useEffect(() => {
  if (!prevIsOpen && popupState.isOpen) {
    if (document.activeElement !== inputRef.current) {
      inputRef.current?.focus();
    }
  }
}, [prevIsOpen, popupState.isOpen]);
```

**Comment by paynecodes** [comment]
@jedwards1211 Wow! Great work on #32. That was much more than I could have anticipated.

**Comment by jedwards1211** [comment]
No problem!
