### ISSUE TITLE
Typescript Error: JSX element type 'PopupState' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by marjan2k** [jcoreio/material-ui-popup-state#4]
![image](https://user-images.githubusercontent.com/14934345/51711153-39e2e680-1ff9-11e9-921a-b2d05df15ca0.png)

**Comment by jedwards1211** [comment]
@marjan2k I haven't used TypeScript, but it generally requires a `.d.ts` file to be present, right?

You could try importing from `material-ui-popup-state/es` instead (you may have to add a rule to whatever bundler you are using to make sure it transpiles `material-ui-popup-state/es`).

**Comment by jedwards1211** [comment]
@marjan2k I just tried to reproduce this by running `tsc --jsx react` on a file that creates a `<PopupState>` element, but I didn't get any errors.  Can you include your typescript config and other information about how you're building the project?  Are you using `awesome-typescript-loader`?

**Comment by marjan2k** [comment]
I am using babel7's typescript.

I think it was an issue with my IDE. The error is no longer there and everything is working fine.

**Comment by jedwards1211** [comment]
Huh, okay.  Well thanks for reporting, I'll close this and if you see problems again just ask me to reopen it :)
