### ISSUE TITLE
Opening menu on right click, i.e. context menu

### ISSUE THREAD

**Issue by abforce** [jcoreio/material-ui-popup-state#40]
How to open the menu on right click? It seems there's no support for context menus.

**Comment by jedwards1211** [comment]
That's true, and `bindTrigger` was a poor name, I should just call it `bindClick`, and add a `bindRightClick` method.

To do it right now you would have to write a click handler that calls `popupState.open(event)` if the right button was clicked.

**Comment by jedwards1211** [comment]
I'll have to research what ARIA attributes should be used for context menus...

**Comment by jedwards1211** [comment]
I had forgotten that the `contextmenu` event is used to handle right clicks to I just added a `bindContextMenu` function for binding the `contextmenu` handler to an element.
