### ISSUE TITLE
Passing functions to onClick

### ISSUE THREAD

**Issue by sankomil** [jcoreio/material-ui-popup-state#49]
I have created a dropdown meny with an Image acting like the trigger like so:

```
    <Image
          alt="Plus"
          aria-controls="long-menu"
          className={classes.plus}
          src={Plus}
          {...bindTrigger(popupState)}
          // onClick={handleClick}
        />
```

I want to pass a function called handleClick to onClick, but if I remove the comment then it overrides the onClick function generated by bindtrigger. I wanted to ask if there is a way to pass handleClick to the generated onClick?

**Comment by jedwards1211** [comment]
Yeah currently there isn't a convenient way to handle this.

If you need to `preventDefault` or `stopPropagation`, there might be a nearby ancestor element you could do so on.  Otherwise, right now you'll have to do
```
onClick={e => {
  // perform additional action
  bindTrigger(popupState).onClick(e)
}}
```

If you just need to perform an additional effect when the popup is opened, and you're using a functional component, I would recommend performing an effect when `popupState.isOpen` changes:

```js
React.useEffect(() => {
  if (popupState.isOpen) {
    // popup was just opened, do something
    // popupState.anchorEl is the element that was clicked
  }
}, [popupState.isOpen])
```

There are several ways I could make the API support this, none I'm 100% happy with, each one is awkward in some way:
###### Possibility 1

```js
{bindTrigger(
  <Image
    alt="Plus"
    onClick={handleClick}
  />,
  popupState
)}
```

###### Possibility 2
```js
<Image
  alt="Plus"
  {...bindTrigger(popupState, {
    onClick: handleClick,   
  })}
/>
```

###### Possibility 3

```js
// at root level:
const TriggerImage = createTrigger(Image)

// somewhere later:
<TriggerImage
  popupState={popupState}
  alt="Plus"
  onClick={handleClick}
/>
```

**Comment by sankomil** [comment]
Yes, I found that running handleClick when the menu is open works for what I am trying to achieve! Thank you for your help!

**Comment by jedwards1211** [comment]
Okay great!  I'm still thinking about maybe releasing some kind of API for merging user event handlers with the injected ones.  I haven't decided yet...

**Comment by sankomil** [comment]
Cool, all the best with that! I'll close the issue now.

**Comment by ifndefdeadmau5** [comment]
> Yeah currently there isn't a convenient way to handle this.
> 
> If you need to `preventDefault` or `stopPropagation`, there might be a nearby ancestor element you could do so on. Otherwise, right now you'll have to do
> 
> ```
> onClick={e => {
>   // perform additional action...and then:
>   bindTrigger(popupState).onClick(e)
> }}
> ```
> 
> If you just need to perform an additional effect when the popup is opened, and you're using a functional component, I would recommend performing an effect when `popupState.isOpen` changes:
> 
> ```js
> React.useEffect(() => {
>   if (popupState.isOpen) {
>     // popup was just opened, do something
>     // popupState.anchorEl is the element that was clicked
>   }
> }, [popupState.isOpen])
> ```
> 
> This is better since if you later need to add additional ways the popup can be opened, all of them will trigger this effect, whereas an onClick handler wouldn't respond to the new ways of opening the popup.
> 
> There are several ways I could make the API support this, none I'm 100% happy with, each one is awkward in some way. Also, does the popup get opened before or after your onClick handler? Some people might want before, some after, and adding an option to control that would make these examples even more bulky. At least if you do the wrapping yourself, as in my example above, you have complete freedom to control this.
> 
> ###### Possibility 1
> ```js
> {bindTrigger(
>   popupState,
>   <Image
>     alt="Plus"
>     onClick={handleClick}
>   />
> )}
> ```
> 
> ###### Possibility 2
> ```js
> <Image
>   alt="Plus"
>   {...bindTrigger(popupState, {
>     onClick: handleClick,   
>   })}
> />
> ```
> 
> ###### Possibility 3
> ```js
> // at root level:
> const TriggerImage = createTrigger(Image)
> 
> // somewhere later:
> <TriggerImage
>   popupState={popupState}
>   alt="Plus"
>   onClick={handleClick}
> />
> ```

Possibility 2 is exactly what I imagined before checking out this issue, which seems pretty straightforward to me. Could this be implemented somehow? I can work on it if you want some help.

**Comment by jedwards1211** [comment]
The main problem with possibility 2 is I can't see any good way to memoize the combined `onClick` function.  It would have to return a new function each time, which would force the receiving component to rerender in most cases.

If you combine them yourself you can at least choose to do so in a `useCallback` earlier in function components, etc.

But we could implement option 2 and just warn in docs that it's always going to return a new `onClick` function.  I feel on the fence about it, what do you think?

**Comment by jedwards1211** [comment]
Actually let me think about it some more.  i guess we could store the previous username `onClick` in a ref in the popup state and use that to memoize.  But I'd need to make the `<PopupState>` component use hooks internally and drop support for React pre-hooks.

**Comment by jedwards1211** [comment]
@andrew2764 that wouldn't currently work because `open`, `close`, etc call the original `toggle` function directly, not whatever one is attached to the modified popup state.  But this makes me think, I should try to change the code to where things like this work, whether or not it's recommended.

**Comment by jedwards1211** [comment]
@ifndefdeadmau5 @andrew2764 I've been thinking about this some more...the main problem with all three possibilities above is, does the custom `onClick` logic run before or after the `bindTrigger` logic?  It could go either way...I can imagine an argument between camps of users who think it should run before and who think it should run after.

So now I'm leaning toward an API with `beforeX`/`afterX` handlers like
```
<Image
  alt="Plus"
  {...bindTrigger(popupState, {
    beforeClick: handleClick,   
  })}
/>
```

**Comment by jedwards1211** [comment]
Okay I decided to go with an API like
```
<Image
  alt="Plus"
  {...chainEventHandlers(
    bindTrigger(popupState),
    { onClick: handleClick },   
  )}
/>
```
This makes specifying the order of the handlers straightforward and would be useful for combining multiple `bindTrigger`s etc.

**Comment by andrew2764** [comment]
Thanks! I ended up using the approach from the sample code in the README 
```js
const button = (
  <Button
    {...bindTrigger(popupState)}
    onClick={(e: React.MouseEvent) => {
      performCustomAction(e)
      bindTrigger(popupState).onClick(e)
    }}
  >
    Open Menu
  </Button>
)
```
The only difference is that I needed to perform an action before the `bindTrigger` logic.

**Comment by jedwards1211** [comment]
@andrew2764 yeah personally I still prefer that approach, the control flow would be more straightforward in a debugger
