### ISSUE TITLE
Sizing

### ISSUE THREAD

**Issue by carlosalvidrez** [jcoreio/material-ui-popup-state#50]
Thanks for building this! 
I am struggling to custom size the Popper... I have tried styling the enclosing DIV, without success.
Any pointers will be apprecaited.

**Comment by jedwards1211** [comment]
Hmmm can you post a code sample?
I'm closing because I'm pretty sure this lib doesn't touch anything that would interfere with popper sizing, but I'm still happy to help.  And if it does turn out there's a problem in this lib we can reopen it

**Comment by carlosalvidrez** [comment]
Thanks, I guess my question is then super basic... do you know where I can find the docs with details around the sizing of popper?

**Comment by jedwards1211** [comment]
Huh, I don't know exactly, I haven't really used popper except for tooltips I think, I assume applying styles to the element you render into the popper will work about the same as applying styles to an absolutely-positioned element, but I'm not sure.
The popper.js docs vaguely mention that it's possible to create a custom size modifier: https://popper.js.org/docs/v2/faq/#my-popper-is-bigger-than-the-viewport-what-do-i-do
And docs on the modifiers here: https://popper.js.org/docs/v1/#modifiers
