### ISSUE TITLE
Hover Poppers stay open under certain condition

### ISSUE THREAD

**Issue by nicegamer7** [jcoreio/material-ui-popup-state#54]
Hi there,

I'm trying to add Poppers that open on hover, so I'm using bindHover. It works, but it seems the Poppers only close if the mouse leaves the trigger without going over the Popper itself. If the mouse goes over the Popper before leaving the trigger, then the Popper stays open even after it leaves both the trigger and the Popper. This is happening on the latest two versions (1.8.0 and 1.8.1), I haven't tried any other versions.

I've uploaded a video [here](https://user-images.githubusercontent.com/8083772/115099643-3bb06180-9f05-11eb-9c27-bc75d294577c.mp4) since I'm not sure if my description was very clear.

**Comment by jedwards1211** [comment]
Thanks for the report and the video!
This was an oversight and fortunately an easy fix.  Once it gets automatically released a comment will appear hear, let me know if it solves the issues for you.

**Comment by nicegamer7** [comment]
Yup, that fixes it for me. Thanks!
