### ISSUE TITLE
Support for MUI v5

### ISSUE THREAD

**Issue by abriginets** [jcoreio/material-ui-popup-state#70]
Hey. MUI v5 beta is out and I was wondering if this library be supporting it?

**Comment by jedwards1211** [comment]
Yes, I'm on vacation at the moment but I'll look into supporting v5 soon

**Comment by barwalker** [comment]
Hope you already have a great vacation! Im looking for news on this.

**Comment by jedwards1211** [comment]
Y'all were just getting peer dependency warnings right?  Everything worked with MUI 5.0.0-beta.1 without any changes to the core code.  In any case, in a moment CI should release a new version that includes `^5.0.0-beta` in the `peerDependencies`.
