### ISSUE TITLE
'deferOpenClose' does not exist in type '{ parentPopupState?: PopupState}'

### ISSUE THREAD

**Issue by slutske22** [jcoreio/material-ui-popup-state#71]
I am trying to recreate and adapt the [cascading hover menus example](https://jcoreio.github.io/material-ui-popup-state/#cascading-hover-menus), and frankly, I'm struggling to get it to work.  When I try to use this code:

```js
  const popupState = usePopupState({
    popupId: `popup-$${id}`,
    variant: "popover",
    deferOpenClose: true
  });
```

I get the typescript error:

`Object literal may only specify known properties, and 'deferOpenClose' does not exist in type '{ parentPopupState?: PopupState | null | undefined; popupId: string | null | undefined; variant: Variant; disableAutoFocus?: boolean | null | undefined; }'.ts(2345)`

Has something changed since the time the example was written and now?  Might this have something to do with having trouble getting the hover to properly open the submenu?

I am using the following versions of the relevant packages:

```
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^4.0.3",
    "@material-ui/core": "^4.12.1",
    "material-ui-popup-state": "^1.8.4",
```

**Comment by jedwards1211** [comment]
whoops, I forgot to remove `deferOpenClose` from the examples.  That property never became part of published API, I went with something else.  I'll fix the examples.
Aside from that the hover stuff is a frustrating mess... some browsers don't seem to emulate mouseover/mouseleave properly on touch devices, and the alternative (using `preventDefault` on `touchstart` events to block that emulation, then handing touch events manually) it cumbersome because that doesn't work in chrome unless you register the `touchstart` listener with `{passive: false}`...going to try to fix it soon, I will probably drop support for React <16.8 when I do.

**Comment by slutske22** [comment]
Yes I was having quite a bit of difficulty using your example, I simply could not get it to work. I managed to find a workaround using refs.  If you're curious, here's my SubMenu component:

```ts
const useStyles = makeStyles({
  touchless: {
    pointerEvents: "none",
    "& .MuiMenu-paper": {
      pointerEvents: "auto"
    }
  }
});

export const Submenu: React.FC<SubmenuProps> = ({
  title,
  popupId,
  children,
  ...props
}) => {
  const parentPopupState = React.useContext(ParentPopupState);

  const buttonRef = useRef<HTMLElement | null>();
  const menuRef = useRef<HTMLElement | null>();

  const popupState = usePopupState({
    popupId,
    variant: "popover",
    parentPopupState
  });

  return (
    <ParentPopupState.Provider value={popupState}>
      <MenuItem
        {...bindHover(popupState)}
        ref={buttonRef as React.RefObject<HTMLLIElement>}
        onMouseLeave={e => {
          if (!menuRef.current?.contains(e.relatedTarget as Node)) {
            popupState.close();
          }
        }}
      >
        <Typography>{title}</Typography>
      </MenuItem>
      <Menu
        {...bindMenu(popupState)}
        ref={menuRef}
        anchorOrigin={{ vertical: "top", horizontal: "right" }}
        transformOrigin={{ vertical: "top", horizontal: "left" }}
        getContentAnchorEl={null}
        MenuListProps={{
          onMouseLeave: e => {
            if (e.relatedTarget !== buttonRef.current) {
              popupState.close();
            }
          }
        }}
        PopoverClasses={{
          root: classes.touchless
        }}
        PaperProps={{
          style: {
            marginLeft: "-10px",
            marginTop: "10px"
          }
        }}
        {...props}
      >
        {children}
      </Menu>
    </ParentPopupState.Provider>
  );
};
```

So I have a `buttonRef`, which is a ref to the `MenuItem` (I think its an `<li>`, and a `menuRef`, which is a ref to the spawned submenu, which is actually a Popover.

So basically when the mouse enters a `MenuItem`, the Submenu opens.  If the uses mouses out of that `MenuItem`, the Submenu will close, *unless* the `relatedTarget` (i.e. where the mouse is going *to*) is a child of the `menuRef` Popover - then it would stay open.  Inversely, when the mouse leaves the Submenu, it will close, *unless* the `relatedTarget` is the `MenuItem` that spawned it.  This is also dependent on removing the pointer events from the Popover, so that the that the `relatedTarget` when mousing out of the Submenu is not just its Popover div.  This seems to be working quite well for me, through various levels of nesting.  Just thought I'd share!

**Comment by jedwards1211** [comment]
Sigh that's exactly what `bindHover` does but it takes any number of nested submenus into account.
Does the cascading hover menus example in the demos not even work on your computer?
Granted, trying to get everything to completely work on mobile has been horrible.

**Comment by slutske22** [comment]
lol is it really?  I guess I didn't read your docs and I ended up [reinventing the wheel.](https://github.com/jcoreio/material-ui-popup-state#using-popover-and-menu-with-bindhover) I don't know why its not working right out of the box then.  The example on the site does indeed work for me, but I did't see any package.json to help me understand what versions of things are being used.  Try for the life of my, I could not seem to get it jiving in my application with the versions I posted above.  My application is beastly, so trying to reproduce in a codesandbox would be a lot of trouble, but perhaps when you update the demos, it might be helpful to have codesandbox demos, so we can see the whole picture.

In any case, I am still leveraging this plugin and its proving very useful.  I guess we can leave this open as its technically about the typing for the `usePopupState` argument.  Thank you for your work on this plugin and your cordiality!

**Comment by jedwards1211** [comment]
Okay, sorry it's causing you trouble, I've definitely been unhappy with how the hover stuff has been working for people.  Aside from the typescript error what problems were you having?  Can you let me know what browser/platform?

**Comment by slutske22** [comment]
I'm using OS Cataline 10.15.7 (19H512), Chrome Version 91.0.4472.114 (Official Build) (x86_64).

Getting this to work as I wanted was *quite* challenging, but kind of fun I guess.  I had issues because our UX wants the initial menu to open on button *click*, and all the submenus to open from hover.  That was a little tricky.  I hated how in the example, every single MenuItem needed to be passed the function to close the menus manually - I felt like that should have been built in to the component.  I came up with a workaround that uses React.cloneElement, and clones the props through....its a little hairy, but its working.  Disentangling a working example from my NDA codebase would be hard, but I can share the code for the few components I used.  Not sure if you're interested, but he's the code (sorry for the long block):

```ts
import React, { useRef } from "react";
import {
  makeStyles,
  Menu,
  MenuItem as MuiMenuItem,
  MenuProps,
  Typography
} from "@material-ui/core";
import {
  usePopupState,
  bindHover,
  bindMenu,
  PopupState
} from "material-ui-popup-state/hooks";
import { withStyles } from "@material-ui/styles";
import clsx from "clsx";


/**
 * Context to track opopup state of a given cascading menu
 */
const ParentPopupState = React.createContext<PopupState | null>(null);

const useSubmenuStyles = makeStyles({
  padding: { ... },
  active: { ... },
  touchless: {
    pointerEvents: "none",
    "& .MuiMenu-paper": {
      pointerEvents: "auto"
    }
  }
});

interface SubmenuProps {
  /**
   * The text of the button that when hovered, spawns a new menu
   */
  buttonText: string;
  /**
   * Id of the popup menu, must be unique on page, used internally by material-ui-popup-state
   */
  popupId: string;
  /**
   * Which direction the submenu should open towards.  Should not be used directly, it will be
   * inherited from the parent CascadingMenu
   */
  direction?: "left" | "right";
  /**
   * The children of the submenu
   */
  children: React.ReactNode | React.ReactNode[];
  /**
   * The function to close the root menu, should not be defined manually, it will
   * be inheritedfrom the parent CascadingMenu
   */
  handleClose?: () => void;
}

/**
 * The Submenu component creates a cascading menu effect, with a new menu spawned from its children.
 * The direction that the submenu opens from is inherited from the parent CascadingMenu.  This component
 * will likely break down if not used as child of CascadingMenu.
 */
export const Submenu: React.FC<SubmenuProps> = ({
  buttonText,
  popupId,
  children,
  direction,
  handleClose,
  ...props
}) => {
  const parentPopupState = React.useContext(ParentPopupState);

  const buttonRef = useRef<HTMLElement | null>();
  const menuRef = useRef<HTMLElement | null>();

  const popupState = usePopupState({
    popupId,
    variant: "popover",
    parentPopupState
  });

  const classes = useSubmenuStyles();

  return (
    <ParentPopupState.Provider value={popupState}>
      <MenuItem
        {...bindHover(popupState)}
        ref={buttonRef as React.RefObject<HTMLLIElement>}
        onMouseLeave={e => {
          if (!menuRef.current?.contains(e.relatedTarget as Node)) {
            popupState.close();
          }
        }}
        className={clsx({ [classes.active]: popupState.isOpen }, "no-click")}
      >
        <Typography>{buttonText}</Typography>
      </MenuItem>
      <Menu
        {...bindMenu(popupState)}
        ref={menuRef}
        anchorOrigin={{
          vertical: "top",
          horizontal: direction === "left" ? "left" : "right"
        }}
        transformOrigin={{
          vertical: "top",
          horizontal: direction === "left" ? "right" : "left"
        }}
        getContentAnchorEl={null}
        MenuListProps={{
          classes: { padding: classes.padding },
          onMouseLeave: e => {
            if (e.relatedTarget !== buttonRef.current) {
              popupState.close();
            }
          }
        }}
        PopoverClasses={{
          root: classes.touchless
        }}
        PaperProps={{
          style: {
            marginLeft: direction === "right" ? "-10px" : "10px",
            marginRight: direction === "left" ? "-10px" : "",
            marginTop: "10px",
            maxHeight: "none"
          }
        }}
        {...props}
      >
        {React.Children.map(children, child => {
          if (React.isValidElement(child)) {
            return React.cloneElement(child, {
              direction,
              onClick: (e: React.MouseEvent) => {
                /**
                 * If child is another nested menu, the element type will be "P", take no action on click
                 * If child is an actionable button, element type will be "LI", fire click handler
                 * and fire handleClose to close the root menu
                 */
                if (!(e.target as HTMLElement).classList.contains("no-click")) {
                  if (child.props.onClick) child.props.onClick(e);
                  if (handleClose) handleClose();
                  popupState.close();
                }
              }
            });
          }
          return child;
        })}
      </Menu>
    </ParentPopupState.Provider>
  );
};

interface ItemGroupProps {
  /**
   * The text of the header LI element
   */
  headerText: string;
  /**
   * The children MenuItems or Submenus in this itemgrop
   */
  children: React.ReactNode | React.ReactNode[];
  /**
   * The function to close the root menu, should not be defined manually, it will
   * be inheritedfrom the parent CascadingMenu
   */
  handleClose?: () => void;
  /**
   * Which direction the submenu should open towards.  Should not be used directly, it will be
   * inherited from the parent CascadingMenu
   */
  direction?: "left" | "right";
}

const useItemGroupStyles = makeStyles({
  header: { ... }
});

export const ItemGroup: React.FC<ItemGroupProps> = (props: ItemGroupProps) => {
  const { headerText, children, handleClose, direction } = props;
  const classes = useItemGroupStyles();
  return (
    <>
      <MenuItem disabled className={classes.header}>
        {headerText}
      </MenuItem>
      {React.Children.map(children, child => {
        if (React.isValidElement(child)) {
          /**
           * Whether or not this child is a nested group or not
           */
          return React.cloneElement(child, {
            direction,
            onClick: (e: React.MouseEvent) => {
              /**
               * If child is another nested menu, element is tagged with 'no-click' class,
               * take no action on click
               * If child is an actionable button, fire click handler
               * and fire handleClose to close the root menu
               */
              if (!(e.target as HTMLElement).classList.contains("no-click")) {
                if (child.props.onClick) child.props.onClick(e);
                if (handleClose) handleClose();
              }
            }
          });
        }
        return child;
      })}
    </>
  );
};

interface CascadingMenuProps extends MenuProps {
  /**
   * The unique HTML id of the menu
   */
  id: string;
  /**
   * Whether or not the menu is open
   */
  open: boolean;
  /**
   * Which direction the menu should cascade towards
   */
  direction: "left" | "right";
  /**
   * The ref of the element used to anchor the MUI Menu component
   */
  anchorRef: React.RefObject<HTMLElement>;
  /**
   * Function to close the root menu
   */
  handleClose: () => void;
  /**
   * Children of the CascadingMenu.  Should only be a MeniItem, Submenu, or ItemGroup
   */
  children: React.ReactNode | React.ReactNode[];
}

export const CascadingMenu: React.FC<CascadingMenuProps> = (
  props: CascadingMenuProps
) => {
  const {
    id,
    open,
    anchorRef,
    handleClose,
    children,
    direction,
    anchorOrigin,
    transformOrigin
  } = props;

  return (
    <Menu
      id={id}
      open={open}
      getContentAnchorEl={null}
      anchorEl={anchorRef.current}
      anchorOrigin={
        anchorOrigin || {
          vertical: "bottom",
          horizontal: "left"
        }
      }
      transformOrigin={
        transformOrigin || {
          vertical: "top",
          horizontal: "left"
        }
      }
      PaperProps={{ square: true, style: { maxHeight: "none" } }}
      keepMounted
      onClose={handleClose}
      MenuListProps={{ style: { padding: 0 } }}
    >
      {React.Children.map(children, child => {
        if (React.isValidElement(child)) {
          return React.cloneElement(child, { handleClose, direction });
        }
        return child;
      })}
    </Menu>
  );
};
```

Sorry for that massive codeblock.  But now I have components for the parent `CascadingMenu`, as well as `Submenu`, and an `ItemGroup` to group `MenuItems`.  I quick storybook looks like this:

![cascade-storybook](https://user-images.githubusercontent.com/52637023/126718568-5c755816-b888-4aed-90c9-4cb67b09b9ec.gif)

So yeah, who knows if that's interesting to you, but if you find any of my code there useful, feel free to incorporate some of it, or, if you think its terrible, dont! 

Again, thanks for this library!

**Comment by jedwards1211** [comment]
I haven't read that code yet, but two things:

* There's a PR underway in MUI to support cascading menus.  It will probably be more convenient to use like what you were going for. (https://github.com/mui-org/material-ui/pull/20591#event-4919771633)

* I wanted to ask, when you initially ran into issues, were you using `import Menu from 'material-ui-popup-state/HoverMenu'`?  I'm wondering if the issue all along was that you weren't using that, and you only added the `pointer-events` CSS workarounds (which `HoverMenu` provides) after debugging the `mouseover`/`mouseout` handlers you wrote.

**Comment by jedwards1211** [comment]
I looked through your code a bit.  Makes sense, I think you might be able to avoid `cloneElement` by creating a `CascadingMenuItem` wrapper component and injecting close handlers etc. via context.  Kinda like how the cascading submenus example uses context to inject parent popup state into the `Submenu` custom component.  Maybe I should update my example with a `CascadingMenuItem` component.

**Comment by slutske22** [comment]
I had *not* initially been using `MenuItem` imported from `material-ui-popup-state/HoverMenu` - I did a bad job of reading the docs.  But even once I did that, I was having trouble getting all the menus to close in sync when there were multiple levels of menus open.

I think using context to inject the `onClick` is a great idea.  Prop drilling through various levels of `cloneElement` was not fun.

**Comment by jedwards1211** [comment]
forgot to close this issue. I finally updated the cascading menu example to pass everything with context -- check it out!

Maybe I should release it eventually but I haven't decided exactly on the API for `CascadingSubmenu`, it's a bit awkward because it encompasses both a `MenuItem` and `Menu` but it's not currently flexible what you can do with the `MenuItem`...

**Comment by slutske22** [comment]
Looks good!  I think as long as the interface for the `CascadingMenuItemProps` extends the interface for `MenuItemProps` from MUI, and all props are passed through to the menu item, a `CascadingMenuItem` can be very flexible.  That's what I've done with my codebase.

Thanks again!
