### ISSUE TITLE
Auto scroll behavior onMouseLeave using Cascading Hover Menu

### ISSUE THREAD

**Issue by caiosamarone** [jcoreio/material-ui-popup-state#73]
I have the following behavior: When I take the mouse off the Menu, the page scrolls all the way down. Is there any way to block this behavior? Thanks. 

Using:    "material-ui-popup-state": "^1.9.0",
              "@material-ui/core": "4.11.3",

**Comment by caiosamarone** [comment]
@jedwards1211

**Comment by jedwards1211** [comment]
Yup, upgrade to 1.9.1 and pass the `disableAutoFocus: true` option to `usePopupState` or `<PopupState>` props.  Take a look at the latest examples on https://jcoreio.github.io/material-ui-popup-state.

I had forgotten the history of this issue and mistakenly removed this from the examples and even broke `disableAutoFocus` in the code a few months ago 😕   So I fixed all of this in 1.9.1.

Note, this will prevent the menu from getting focus, and the arrow keys won't work on it.  If you want the menu to get focus on hover but restore focus to the prior active element without scrolling when the menu is closed, let me know; I can talk to the MUI folks about adding a feature to their `Unstable_TrapFocus`, which is what restores the focus and causes scrolling by default.

**Comment by jedwards1211** [comment]
Actually...I'm releasing another fix that will `disableAutoFocus` to `true` when the popup is opened by hover or focus.  That will be 1.9.2.

**Comment by caiosamarone** [comment]
Thanks!!!

**Comment by caiosamarone** [comment]
Also, great job. This was perfectly what I was searching for! 

Beside that, do you know if Material UI will launch their own cascading hover menu? I saw that a lot of people were asking for this

**Comment by jedwards1211** [comment]
I've seen an in-progress PR in their repo for cascading menus, so probably
