### ISSUE TITLE
Hover Menu does not close when page is scrolled in mobile

### ISSUE THREAD

**Issue by benjaminlim00** [jcoreio/material-ui-popup-state#84]

**Comment by jedwards1211** [comment]
Hey sorry I missed this, does the menu at least close when you tap outside of it?  I'm not sure about responding to scroll events as a default behavior, but I'd be open to talking about an option for it

**Comment by 7ruth** [comment]
Had this exact issue on mobile with scrollable content. Quick solution was to wrap in mui's clickAwayListener:

```
import ClickAwayListener from "@mui/material/ClickAwayListener";

<ClickAwayListener onClickAway={menuState.close}>
                      <HoverMenu
```
