### ISSUE TITLE
On mouse out is not working with bindHover(popupState) method

### ISSUE THREAD

**Issue by venu-pantangi** [jcoreio/material-ui-popup-state#87]
On mouse hover the events are working properly but on mouse out it's not removing the popper or popover, is there a way to close hover event on mouse out something like **bindOut(popuState)**?

OnClick event also not triggering on the same, is there a way to add the click event too?

```
<PopupState variant="popover" popupId="demo-popup-popover">
  {(popupState) => (
    <div>
      <Button variant="contained" onClick={() => alert("sdf")} {...bindHover(popupState)}>
        Open Popover
      </Button>
      <Popover
        {...bindPopover(popupState)}
        anchorOrigin={{
          vertical: 'bottom',
          horizontal: 'center',
        }}
        transformOrigin={{
          vertical: 'top',
          horizontal: 'center',
        }}
      >
        <Typography sx={{ p: 2 }}>The content of the Popover.</Typography>
      </Popover>
    </div>
  )}
</PopupState>
```

In the above code snippet onClick event should trigger and get the alert as well

Thanks in advance :)

**Comment by jedwards1211** [comment]
You need to use `import HoverPopover from 'material-ui-popup-state/HoverPopover'` with `bindHover`.  The default `Popover` from MUI interferes with mouseover and mouseout events.  See https://github.com/jcoreio/material-ui-popup-state#using-popover-and-menu-with-bindhover

To trigger the popover on click add `{...bindTrigger(popupState)}`

Let me know if this solves your problem

**Comment by jedwards1211** [comment]
@venu-pantangi did you have any luck with the solutions in my previous comment?
