### ISSUE TITLE
Error in production when building with vite 2.7+

### ISSUE THREAD

**Issue by faradaytrs** [jcoreio/material-ui-popup-state#88]
It was fine until i updated vite to 2.7. It uses rollup internally. 
When i remove all uses of this library problem also disappears. 
Error is:
TypeError: gM is not a function
    at vM (core.js:28)
    at core.js:24

I tried to disable minification and it produces something like: interopRequireWildcard error
Name depends on build due to minification, but error is the same every time. Any ideas why could cause the issue?

Now i'm using:
react 17.0.2
Vite 2.7.6
material-ui-popup-state: 2.0.0

**Comment by dixso** [comment]
Hi,
I had the same problem, I fixed using the _ES_ compilation:

Instead of import this:
`import { PopupState } from 'material-ui-popup-state/core';`

Try this:
`import { PopupState } from 'material-ui-popup-state/es/core';`

Regards

**Comment by jedwards1211** [comment]
Thank goodness I have the ES build in place, it's not very well documented in any of my packages...definitely make sure to use only one or the other.

Before long I'll have to devote more attention to the whole ESM/CJS mess...

**Comment by dantman** [comment]
Releasing a new major that uses package.json:exports would probably be warranted. That'll take care of making sure that Vite/WebPack5/etc all use the ESM version.
