### ISSUE TITLE
bindHover doesn't work on Material v4

### ISSUE THREAD

**Issue by DeylEnergy** [jcoreio/material-ui-popup-state#9]
Hello. I use the version with Hooks for cascading menus. The problem is bindHover doesn't work on version 4. Actually, it works till the latest v4 alpha. Could you please help with a workaround? Here is [codesandbox](https://codesandbox.io/s/material-demo-zs3if). Thank you for your time.

**Comment by piotrf** [comment]
I can confirm I’m getting the same issue with a bunch of errors along those lines: `Warning: Failed prop type: The prop 'open' is marked as required in 'TrapFocus', but its value is 'null'.`—could these possibly be related?

**Comment by jedwards1211** [comment]
I see v4 is released now, I'll get working on this

**Comment by jedwards1211** [comment]
fortunately it was simple, they dropped support for `ModalClasses` in v4 so I had to apply `pointerEvents: 'none'` using inline `style` on the `Modal`.  Release coming in just a moment

**Comment by piotrf** [comment]
Excellent news, looking forward to giving it a whirl.

**Comment by piotrf** [comment]
Thanks for looking into this @jedwards121. `1.4.0` indeed fixed my `bindHover` issues. I still get a bunch of `ForwardRef` warnings.

**Comment by jedwards1211** [comment]
@piotrf are you trying to pass a `ref` to `HoverMenu` or `HoverPopover`?  And if so why?

**Comment by jedwards1211** [comment]
@piotrf turns out Menu injects refs into its children, more information about that at the bottom of #11.
