### ISSUE TITLE
Support for Dialog

### ISSUE THREAD

**Issue by iacobfred** [jcoreio/material-ui-popup-state#90]
Thanks for this!
Could this library also support state for the MUI Dialog component (https://mui.com/components/dialogs/)?

**Comment by iacobfred** [comment]
`variant="popover"` seems to play nicely with `Dialog`, actually.

**Comment by jedwards1211** [comment]
Yeah sounds like that would basically work but it injects ARIA properties to the dialog that may not be appropriate for it.  It would probably make sense to support `variant="dialog"`, I'll look into it

**Comment by dohomi** [comment]
That would be a great addition to this library
