### ISSUE TITLE
Issue with mapping 

### ISSUE THREAD

**Issue by ahmadwrites** [jcoreio/material-ui-popup-state#96]
When I use  the hooks for mapping, only the last data is rendered. I cannot use an array and map a bunch of menus as a result

**Comment by jedwards1211** [comment]
You could use the `<PopupState>` component provided by `material-ui-popup-state` for each value in the map.  Otherwise you'll have to create your own custom component that calls `usePopupState` once, and render one instance of that custom component for each value you're mapping\
