### ISSUE TITLE
position menu based on cursor position when using bindContextMenu

### ISSUE THREAD

**Issue by amitozalvo** [jcoreio/material-ui-popup-state#97]
Hello, when using bindContextMenu, the menu will always be opened at the same place regardless of the cursor position.

I wanted to know if there's a way to get it to work like a usual context menu where it's obvious the cursor is responsible to be opening the menu

Thanks!

**Comment by dbfernandes** [comment]
I had the same problem, I would really like a solution for this.

**Comment by jedwards1211** [comment]
I just pushed a change where the menu/popover will be positioned to the cursor position by default when `bindContextMenu` is used.  Once the CI build passes the new version will be released

**Comment by dbfernandes** [comment]
Thank you very much! It worked perfectly!
